ronin-co/syntax

src/model/model.ts
src/model/utils/serializers.ts
tests/model.test.ts

This PR allows to create nested fields like: 
```ts
const Account = model({
slug: 'account',
pluralSlug: 'accounts',
fields: {
invoice: {
number: string({ required: true }),
date: date(),
},
},
});
```

Added nested fields

---

.vscode/settings.json
src/model/model.ts
src/model/utils/errors.ts
tests/model.test.ts

Added `RoninError` to provide more meaningful error messages to users. Additionally, we now validate if a user attempts to define the `id` field and throw an error in such cases. While this is already flagged by the linter, it will now also cause a failure when running the schemas.

Enforce error on defining `id` field

---

biome.json
src/utils/serializers.ts

This pull request addresses an issue where a dynamic import was causing compilation errors in Next.js routes for our customers. The dynamic import has been removed to resolve this problem.

Remove dynamic import

---

src/queries.ts
src/utils/index.ts
tests/queries.test.ts

This change was missing from https://github.com/ronin-co/syntax/pull/16 and makes it possible to already open the function call at the root of a query (right after the query type).

Allow function calls at root of query

---

src/queries.ts
src/schema/primitives.ts
src/utils/serializers.ts
tests/queries.test.ts
tests/schema/model.test.ts
tests/utils/serializers.test.ts

This change ensures that schema queries can make use of the same syntax that is used for defining the database schema in code, with exactly the same syntax helpers as well:
```typescript
import { create } from 'ronin';
import { string } from 'ronin/schema';
await create.model({
slug: 'account',
fields: {
handle: string().required()
}
});
```
In an upcoming iteration, the `ronin/schema` export will also provide other syntax utilities, such as functions like `json_patch` that SQLite provides natively.

Provide full model syntax for queries

---

src/queries.ts
src/utils/serializers.ts
tests/queries.test.ts
tests/utils/serializers.test.ts

This change ensures that batches of queries are reliably serialized with the least amount of logic possible.

Ensure reliable query serialization

---

src/queries.ts
tests/queries.test.ts

This change resolves a bug reported [on Discord](https://discord.com/channels/1099977902629589095/1099977903678173206/1328097169873440871) by ensuring that queries are able to correctly detect whether they are run inside a batch transaction, or not.

Ensure correct batch context for queries

---

src/queries/index.ts
tests/queries.test.ts

This change ensures that queries correctly accept `Date` objects.

Support `Date` objects in queries

---

tests/queries.test.ts

This change was missing from https://github.com/ronin-co/syntax/pull/27 and improves the test for asserting blob-like structures as values (such as `File`) even further, by simplifying the test.

Ensure simpler test assertions

---

src/queries/index.ts
tests/queries.test.ts

I noticed that the test `using field with file` was not actually working correctly, because `toHaveBeenCalledWith` in Bun doesn't seem to correctly handle objects like `File` or `Date`.
Meaning that, in the final comparison, it considers `{}` (an empty object) and the actual object (e.g. `Date`) to be the same, which is of course not true.

Ensure correct test assertions

---

src/queries/index.ts
tests/queries.test.ts

This change ensures that query instructions containing `undefined` as their value do not cause a crash and are instead automatically ignored in the final JSON serialization.

Gracefully handle undefined instructions

---

src/schema/model.ts
tests/schema/model.test.ts

This PR updates the `FieldsToTypes` type to change the default or failover type from `never` to `object`. This fixes an issue where the types inferred from a schema model were not getting flattened into a single object.

Fixed schema inferred type flattening

---

src/queries/index.ts
src/queries/statements.ts
tests/queries/index.test.ts
tests/queries/statements.test.ts

This change adds the necessary syntax utilities for running raw SQL from the TypeScript client.

Added syntax utils for SQL

---

src/schema/model.ts
src/schema/primitives.ts

This PR applies both some minor refactoring changes, along with updating the necessary types in order to fix the inferred types of fields to mark them as `null` if they are not required.

Ensure inferred fields are marked as `null`

---

src/schema/primitives.ts

This PR fixes a small regression included as part of #32 where the `defaultValue` property was not correctly isolating the callback type. So it was assuming the property would only ever allow a callback function rather than a literal.

Fixed model field expression default value type

---

src/queries/statements.ts
tests/queries/statements.test.ts

This change ensures that SQL statements spanning multiple lines are parsed just fine.

Support multi-line SQL statements

---

src/schema/primitives.ts

This PR adds some TSDoc example code snippets to all field primitives to give the user a easier quick glance on how possibly to use such fields.

Added TSDoc example snippets to all field primitives

---

examples/models.ts
src/schema/model.ts
tests/schema/model.test.ts

This PR makes a small change to both the `indexes` & `triggers` properties of the `model` function options such that instead of an array of properties we instead now use a key/value object.
This has been implemented in order to make these 2 properties more consistent with the `fields` property.

Refactored `indexes` & `triggers` object structures

---

src/schema/primitives.ts

This PR fixes a small oversight on my part as part of #8 where the module being imported in the example snippets refer to this package itself. However the real world use case is that they are to be used with the `ronin` package. As such I have updated the examples to use the import from the `ronin` package instead.

Fixed TSDoc comments examples

---

src/queries/index.ts
src/utils/index.ts
tests/queries/index.test.ts

It is perfectly normal to place a value such as `null` inside a batch, because that makes it easy to construct batches with multiple queries, where each one is constructed using a ternary. Without placeholders like those, all the values after it would of course shift one array index upward, which is not an option.
The latest syntax no longer supports these kinds of values, so I'm adding back support for them.

Prevent crash if batch contains empty values

---

examples/models.ts
src/schema/model.ts
tests/schema/model.test.ts

This PR fixes a small regression introduced as part of #52 where the types for a model `presets` property were incorrectly updated.

Fix model `presets` object types

---

src/helpers/functions.ts
tests/helpers/expressions.test.ts

This PR adds the core sql function [`replace()`](https://www.sqlite.org/lang_corefunc.html#replace).

Added support for `replace()`

---

src/queries/index.ts
src/schema/model.ts

This change ensures that the `model()` function always returns an object and never a JS proxy.
As a result, the migration commands in the CLI will work as expected again.

Ensure correct behavior for model definition

---

src/schema/primitives.ts

This change ensures that the types of Link fields are always correct and up-to-date.

Ensure up-to-date types for link fields

---

src/queries/statements.ts
tests/queries/statements.test.ts

This change fixes a small problem with the `sql` function where if you placed any `--` comments inside template string it will fail the request because there is no way to determine the end of the comment. Instead we will strip any & all comments from raw SQL queries.

Automatically strip out any comments in SQL templates

---

bun.lock
package.json
src/schema/primitives.ts

This change ensures that model entities (fields, presets, etc.) that were automatically generated by RONIN are clearly marked as such, to prevent them from getting mixed up with the ones that were provided explicitly.
Originally, the change was landed in https://github.com/ronin-co/compiler/pull/157.

Identify system-generated model entities

---

bun.lock
package.json

This change was missing from ronin-co/compiler#158 and ensures that all query types are accessible in a single constant.
Originally, the change was landed in ronin-co/compiler#159.

Export all query types combined

---

src/queries/index.ts
tests/queries/index.test.ts

At the moment, whenever an error occurs inside a `batch(() => [])` call, the batch context is not reset correctly, which is making all individual queries that are run **after the batch** think that they are running **inside the batch**.
This change right here ensures that the batch context is always reset, even in the case that an error is thrown.

Correctly reset batch context if an error is thrown

---

bun.lock
package.json

At the moment, creating and updating model entities causes JSON metadata to be written as strings into the meta table, which is not expected, since the stored metadata should instead be raw JSON.
The current change resolves this issue and also removes an unnecessary change that was introduced in https://github.com/ronin-co/compiler/pull/82.
Originally, the change was landed in https://github.com/ronin-co/compiler/pull/160.

Correctly serialize JSON when updating meta table

---

bun.lock
package.json
src/queries/types.ts

This change de-couples the `ResultRecord` type from the `@ronin/compiler` package in order to hard code the type with improve readability and documentation.

Improve `ResultRecord` type readability

---

bun.lock
package.json

As it turns out, bundlers must know the unique origin of a piece of code (e.g. a function) in order to de-duplicate it.
For example, if two packages both bundle the same package x, then the code of package x will be duplicated in both of those packages.
Now, even if something imports those packages and runs a bundler, the code of package x will still be present twice, since the bundler is unable to know that both packages are using the same package x at the same version.
We therefore have two choices: Put all of our organization's code into a single monorepo (where deduping happens because all dependencies are known locally, which is not an option for us) or use peer dependencies (this is what we will do).

Use peer dependencies

---

src/global.d.ts
src/queries/index.ts

This change ensures that queries always correctly detect whether they are running inside a batch, by ensuring that the context does not depend on a specific file being imported, but instead on a global variable.

Ensure reliable batch context

---

src/queries/index.ts

Browsers don't have a `global` variable (it'd be `window` there), since `global` is Node.js-specific, as a replacement for `window`, which is not available there.
The [globalThis](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/globalThis) variable is available in all JavaScript runtimes, however, so we can use that.

Make batch context work in browser

---

bun.lock
package.json

The name "RoninError" is pretty meaningless, since it might stem from any component of the RONIN platform.
With the name "CompilerError", it becomes clear that the error stems from the compiler.
Originally, the change was landed in https://github.com/ronin-co/compiler/pull/181.

Provide helpful name for compiler errors
